export const translations = {
  en: {
    home: 'Home',
    search: 'Search',
    signIn: 'Sign In',
    register: 'Register',
    profile: 'Profile',
    logout: 'Logout',
    language: 'Language',
    categories: 'Categories',
    library: 'Library',
    account: 'Account',
    discover: 'Discover',
    read: 'Read',
    learn: 'Learn',
    yourDigitalBookshelf: 'Your digital bookshelf',
    discoverBooks: "Discover books you'll love.",
    browseBooks: 'Browse Books',
    findNextBook: 'Find your next book',
    searchLibrary: 'Search the library',
    searchBy: 'Search by title, author, ISBN, category, or keyword.',
    searchPlaceholder: 'Search title, author, ISBN...',
    searching: 'Searching...',
    searchingLibrary: 'Searching the Readify library...',
    noBooks: 'No books found',
    tryAnother: 'Try another title, author, ISBN, or keyword.',
    welcomeBack: 'Welcome Back',
    signInContinue: 'Sign in to continue reading your books.',
    email: 'Email',
    password: 'Password',
    createAccount: 'Create Account',
    name: 'Name',
    confirmPassword: 'Confirm Password',
    cancel: 'Cancel',
    save: 'Save',
    saving: 'Saving...',
    editProfile: 'Edit Profile',
    readifyMember: 'Readify Member',
    about: 'About',
    books: 'Books',
    bookmarks: 'Bookmarks',
    progress: 'Progress',
    myLibrary: 'My Library',
    savedBooks: 'Your saved books',
    readingProgress: 'Reading Progress',
    continueReading: 'Continue your reading',
    signOut: 'Sign Out',
    signOutReadify: 'Sign out of Readify',
    yourReadingSpace: 'Your reading space',
    loadingLibrary: 'Loading your library...',
    libraryEmpty: 'Your library is empty',
    exploreBooks: 'Explore books →',
    savedBooksTitle: 'Saved books',
    removeLibrary: 'Remove from library',
    keepGoing: 'Keep going',
    loadingProgress: 'Loading your progress...',
    continueWhereLeft: 'Continue reading where you left off.',
    readNow: 'Read now →',
    listen: 'Listen',
    bookNotFound: 'Book not found',
    backToSearch: 'Back to search',
    backDiscover: '← Back to discover',
    aboutBook: 'About this book',
    featured: 'Featured books',
    popular: 'Popular right now',
    explore: 'Explore →',
    viewAll: 'View all →',
    allBooks: 'All books',
    readifyLibrary: 'Readify Library',
    noBooksYet: 'No books available yet',
    uploadBookAdmin: 'Upload a book from the admin page to add it to the Readify library.',
    curated: 'Curated for you',
    readersChoosing: 'Readers are choosing',
    browseInterest: 'Browse by interest',
    exploreCategories: 'Explore categories',
    keepJourney: 'Keep your journey',
    nextChapter: 'Your next chapter starts here.',
    openLibrary: 'Open my library',
    fullName: 'Full Name',
    bio: 'Bio',
    emailCannot: 'Email cannot be changed here.',
    tellReaders: 'Tell readers something about yourself...',
    uploadBook: 'Upload Book',
    readifyAdmin: 'Readify Admin',
    bookTitle: 'Book Title',
    description: 'Description',
    authorName: 'Author Name',
    publishedYear: 'Published Year',
    languageCode: 'Language Code',
    languageName: 'Language Name',
    rightsStatus: 'Rights Status',
    publicDomain: 'Public Domain',
    openLicense: 'Open License',
    authorized: 'Authorized',
    unknown: 'Unknown',
    coverUrl: 'Cover URL',
    sourceUrl: 'Source URL',
    selectCategory: 'Select a category',
    selectedFile: 'Selected file',
    bookFile: 'Book File',
    settings: 'Settings',
    forgotPassword: 'Forgot password?',
    joinReadify: 'Join Readify and start building your library.',
    addToLibrary: 'Add to library',
    addToLibraryQuestion: 'Add to Library?',
    addToLibraryDescription: 'Do you want to add this book to your personal library?',
    no: 'No',
    yes: 'Yes',
    loadingCategories: 'Loading categories...',
    loadingBooks: 'Loading books...',
    viewAllBooks: 'View all books',
    heroDescription: 'Find your next great book, build your personal library, and keep your reading journey moving wherever you go.',
    uploadAdmin: 'Upload a book from the admin page to add it to the Readify library.',
    loadingBook: 'Loading book...',
    unableOpenBook: 'Unable to open this book',
    backBooks: '← Back to books',
    noOriginalFile: 'No original file',
    backBook: '← Back to book',
    back: '← Back',
    page: 'Page',
    previous: '← Previous',
    go: 'Go',
    next: 'Next →',
    loadingPdf: 'Loading PDF...',
    unablePdf: 'Unable to display this PDF.',
    previousPage: '← Previous Page',
    nextPage: 'Next Page →',
    catFiction: 'Fiction',
    catBusiness: 'Business',
    catSelfDevelopment: 'Self Development',
    catLiterature: 'Literature',
    catBiography: 'Biography',
    catHistory: 'History',
    catEducation: 'Education',
    catTechnology: 'Technology',
    catReligion: 'Religion',
    catRomance: 'Romance',
    catChildren: "Children's Books",
    catScience: 'Science',
    catPhilosophy: 'Philosophy',
    catEconomics: 'Economics',
    catChristianBible: 'Christian Bible',
    creatingAccount: 'Creating Account...',
    validEmailHint: 'Gmail, Yahoo, Hotmail, Outlook, or another valid email.',
    categoryHint: 'Select the category that best describes this book.',
  },
  rw: {
    home: 'Ahabanza',
    search: 'Shakisha',
    signIn: 'Injira',
    register: 'Iyandikishe',
    profile: 'Umwirondoro',
    logout: 'Sohoka',
    language: 'Ururimi',
    categories: 'Ibyiciro',
    library: 'Isomero',
    account: 'Konti',
    discover: 'Menya',
    read: 'Soma',
    learn: 'Iga',
    yourDigitalBookshelf: 'Isomero ryawe rya digitale',
    discoverBooks: 'Menya ibitabo uzakunda.',
    browseBooks: 'Reba Ibitabo',
    findNextBook: 'Shaka igitabo gikurikira',
    searchLibrary: 'Shakisha mu isomero',
    searchBy: 'Shakisha ukoresheje umutwe, umwanditsi, ISBN, icyiciro cyangwa ijambo.',
    searchPlaceholder: 'Shakisha umutwe, umwanditsi, ISBN...',
    searching: 'Birashakishwa...',
    searchingLibrary: 'Birashakishwa mu isomero rya Readify...',
    noBooks: 'Nta bitabo byabonetse',
    tryAnother: 'Gerageza undi mutwe, mwanditsi, ISBN cyangwa ijambo.',
    welcomeBack: 'Murakaza neza',
    signInContinue: 'Injira ukomeze gusoma ibitabo byawe.',
    email: 'Imeyili',
    password: 'Ijambobanga',
    createAccount: 'Fungura konti',
    name: 'Amazina',
    confirmPassword: 'Emeza ijambobanga',
    cancel: 'Hagarika',
    save: 'Bika',
    saving: 'Birabikwa...',
    editProfile: 'Hindura umwirondoro',
    readifyMember: 'Umunyamuryango wa Readify',
    about: 'Ibyerekeye',
    books: 'Ibitabo',
    bookmarks: 'Ibimenyetso',
    progress: 'Iterambere',
    myLibrary: 'Isomero ryanjye',
    savedBooks: 'Ibitabo wabikiye',
    readingProgress: 'Iterambere ryo gusoma',
    continueReading: 'Komeza gusoma',
    signOut: 'Sohoka',
    signOutReadify: 'Sohoka muri Readify',
    yourReadingSpace: 'Umwanya wawe wo gusoma',
    loadingLibrary: 'Isomero ryawe ririmo gufunguka...',
    libraryEmpty: 'Isomero ryawe nta gitabo ririmo',
    exploreBooks: 'Shakisha ibitabo →',
    savedBooksTitle: 'Ibitabo wabikiye',
    removeLibrary: 'Kuramo mu isomero',
    keepGoing: 'Komeza',
    loadingProgress: 'Iterambere ryawe ririmo gufunguka...',
    continueWhereLeft: 'Komeza usome aho wari ugeze.',
    readNow: 'Soma nonaha →',
    listen: 'Tega amatwi',
    bookNotFound: 'Igitabo nticyabonetse',
    backToSearch: 'Subira ku gushakisha',
    backDiscover: '← Subira ku kuvumbura',
    aboutBook: 'Ibyerekeye iki gitabo',
    featured: 'Ibitabo byatoranyijwe',
    popular: 'Bikunzwe ubu',
    explore: 'Vumbura →',
    viewAll: 'Reba byose →',
    allBooks: 'Ibitabo byose',
    readifyLibrary: 'Isomero rya Readify',
    noBooksYet: 'Nta bitabo biraboneka',
    uploadBookAdmin: 'Ohereza igitabo kuri Admin kugira ngo cyongerwe mu isomero rya Readify.',
    curated: 'Byatoranyijwe kuri wowe',
    readersChoosing: 'Ibyo abasomyi bahitamo',
    browseInterest: 'Shakisha ukurikije ibyo ukunda',
    exploreCategories: 'Vumbura ibyiciro',
    keepJourney: 'Komeza urugendo rwawe',
    nextChapter: 'Igice gikurikira gitangirira hano.',
    openLibrary: 'Fungura isomero ryanjye',
    fullName: 'Amazina yose',
    bio: 'Umwirondoro mugufi',
    emailCannot: 'Imeyili ntishobora guhindurirwa hano.',
    tellReaders: 'Bwira abasomyi ikintu kuri wowe...',
    uploadBook: 'Ohereza Igitabo',
    readifyAdmin: 'Readify Admin',
    bookTitle: "Umutwe w'igitabo",
    description: 'Ibisobanuro',
    authorName: "Amazina y'umwanditsi",
    publishedYear: 'Umwaka cyasohotse',
    languageCode: "Kode y'ururimi",
    languageName: "Izina ry'ururimi",
    rightsStatus: 'Uburenganzira',
    publicDomain: 'Rusange nta burenganzira bwihariye',
    openLicense: 'Uruhushya rufunguye',
    authorized: 'Byemewe',
    unknown: 'Kitazwi',
    coverUrl: "URL y'igifuniko",
    sourceUrl: "URL y'isoko",
    selectCategory: 'Hitamo icyiciro',
    selectedFile: 'Dosiye wahisemo',
    bookFile: "Dosiye y'igitabo",
    settings: 'Igenamiterere',
    forgotPassword: 'Wibagiwe ijambobanga?',
    joinReadify: 'Injira muri Readify utangire kubaka isomero ryawe.',
    addToLibrary: 'Ongeramo mu isomero',
    addToLibraryQuestion: 'Ongeramo mu isomero?',
    addToLibraryDescription: 'Urashaka kongera iki gitabo mu isomero ryawe bwite?',
    no: 'Oya',
    yes: 'Yego',
    loadingCategories: 'Ibyiciro birimo gufunguka...',
    loadingBooks: 'Ibitabo birimo gufunguka...',
    viewAllBooks: 'Reba ibitabo byose',
    heroDescription: 'Shaka igitabo cyiza gikurikira, wubake isomero ryawe bwite, kandi ukomeze urugendo rwawe rwo gusoma aho waba uri hose.',
    uploadAdmin: 'Ohereza igitabo kuri Admin kugira ngo cyongerwe mu isomero rya Readify.',
    loadingBook: 'Igitabo kirimo gufunguka...',
    unableOpenBook: 'Ntibishoboka gufungura iki gitabo',
    backBooks: '← Subira ku bitabo',
    noOriginalFile: "Nta dosiye y'umwimerere",
    backBook: '← Subira ku gitabo',
    back: '← Subira',
    page: 'Ipaji',
    previous: '← Ibanjirije',
    go: 'Genda',
    next: 'Ikurikira →',
    loadingPdf: 'PDF irimo gufunguka...',
    unablePdf: 'Ntibishoboka kwerekana iyi PDF.',
    previousPage: '← Ipaji ibanziriza',
    nextPage: 'Ipaji ikurikira →',
    catFiction: 'Ibihimbano',
    catBusiness: 'Ubucuruzi',
    catSelfDevelopment: 'Kwiteza imbere',
    catLiterature: 'Ubuvanganzo',
    catBiography: "Ubuzima bw'umuntu",
    catHistory: 'Amateka',
    catEducation: 'Uburezi',
    catTechnology: 'Ikoranabuhanga',
    catReligion: 'Idini',
    catRomance: 'Urukundo',
    catChildren: "Ibitabo by'abana",
    catScience: 'Siyansi',
    catPhilosophy: 'Filozofiya',
    catEconomics: 'Ubukungu',
    catChristianBible: 'Bibiliya ya Gikristo',
    creatingAccount: 'Konti irimo gukorwa...',
    validEmailHint: 'Gmail, Yahoo, Hotmail, Outlook cyangwa indi email yemewe.',
    categoryHint: 'Hitamo icyiciro gisobanura neza iki gitabo.',
  },
  fr: {
    home: 'Accueil',
    search: 'Rechercher',
    signIn: 'Se connecter',
    register: "S'inscrire",
    profile: 'Profil',
    logout: 'Déconnexion',
    language: 'Langue',
    categories: 'Catégories',
    library: 'Bibliothèque',
    account: 'Compte',
    discover: 'Découvrir',
    read: 'Lire',
    learn: 'Apprendre',
    yourDigitalBookshelf: 'Votre bibliothèque numérique',
    discoverBooks: 'Découvrez les livres que vous aimerez.',
    browseBooks: 'Parcourir les livres',
    findNextBook: 'Trouvez votre prochain livre',
    searchLibrary: 'Rechercher dans la bibliothèque',
    searchBy: 'Recherchez par titre, auteur, ISBN, catégorie ou mot-clé.',
    searchPlaceholder: 'Rechercher titre, auteur, ISBN...',
    searching: 'Recherche...',
    searchingLibrary: 'Recherche dans la bibliothèque Readify...',
    noBooks: 'Aucun livre trouvé',
    tryAnother: 'Essayez un autre titre, auteur, ISBN ou mot-clé.',
    welcomeBack: 'Bon retour',
    signInContinue: 'Connectez-vous pour continuer à lire vos livres.',
    email: 'E-mail',
    password: 'Mot de passe',
    createAccount: 'Créer un compte',
    name: 'Nom',
    confirmPassword: 'Confirmer le mot de passe',
    cancel: 'Annuler',
    save: 'Enregistrer',
    saving: 'Enregistrement...',
    editProfile: 'Modifier le profil',
    readifyMember: 'Membre Readify',
    about: 'À propos',
    books: 'Livres',
    bookmarks: 'Signets',
    progress: 'Progression',
    myLibrary: 'Ma bibliothèque',
    savedBooks: 'Vos livres enregistrés',
    readingProgress: 'Progression de lecture',
    continueReading: 'Continuez votre lecture',
    signOut: 'Se déconnecter',
    signOutReadify: 'Se déconnecter de Readify',
    yourReadingSpace: 'Votre espace de lecture',
    loadingLibrary: 'Chargement de votre bibliothèque...',
    libraryEmpty: 'Votre bibliothèque est vide',
    exploreBooks: 'Explorer les livres →',
    savedBooksTitle: 'Livres enregistrés',
    removeLibrary: 'Retirer de la bibliothèque',
    keepGoing: 'Continuez',
    loadingProgress: 'Chargement de votre progression...',
    continueWhereLeft: 'Continuez là où vous vous êtes arrêté.',
    readNow: 'Lire maintenant →',
    listen: 'Écouter',
    bookNotFound: 'Livre introuvable',
    backToSearch: 'Retour à la recherche',
    backDiscover: '← Retour à la découverte',
    aboutBook: 'À propos de ce livre',
    featured: 'Livres sélectionnés',
    popular: 'Populaires maintenant',
    explore: 'Explorer →',
    viewAll: 'Voir tout →',
    allBooks: 'Tous les livres',
    readifyLibrary: 'Bibliothèque Readify',
    noBooksYet: 'Aucun livre disponible pour le moment',
    uploadBookAdmin: "Téléversez un livre depuis la page admin pour l'ajouter à la bibliothèque Readify.",
    curated: 'Sélectionnés pour vous',
    readersChoosing: 'Les lecteurs choisissent',
    browseInterest: 'Parcourir par intérêt',
    exploreCategories: 'Explorer les catégories',
    keepJourney: 'Poursuivez votre parcours',
    nextChapter: 'Votre prochain chapitre commence ici.',
    openLibrary: 'Ouvrir ma bibliothèque',
    fullName: 'Nom complet',
    bio: 'Biographie',
    emailCannot: "L'e-mail ne peut pas être modifié ici.",
    tellReaders: 'Dites quelque chose de vous aux lecteurs...',
    uploadBook: 'Téléverser un livre',
    readifyAdmin: 'Administration Readify',
    bookTitle: 'Titre du livre',
    description: 'Description',
    authorName: "Nom de l'auteur",
    publishedYear: 'Année de publication',
    languageCode: 'Code langue',
    languageName: 'Nom de la langue',
    rightsStatus: 'Statut des droits',
    publicDomain: 'Domaine public',
    openLicense: 'Licence ouverte',
    authorized: 'Autorisé',
    unknown: 'Inconnu',
    coverUrl: 'URL de couverture',
    sourceUrl: 'URL source',
    selectCategory: 'Sélectionnez une catégorie',
    selectedFile: 'Fichier sélectionné',
    bookFile: 'Fichier du livre',
    settings: 'Paramètres',
    forgotPassword: 'Mot de passe oublié ?',
    joinReadify: 'Rejoignez Readify et commencez à construire votre bibliothèque.',
    addToLibrary: 'Ajouter à la bibliothèque',
    addToLibraryQuestion: 'Ajouter à la bibliothèque ?',
    addToLibraryDescription: 'Voulez-vous ajouter ce livre à votre bibliothèque personnelle ?',
    no: 'Non',
    yes: 'Oui',
    loadingCategories: 'Chargement des catégories...',
    loadingBooks: 'Chargement des livres...',
    viewAllBooks: 'Voir tous les livres',
    heroDescription: 'Trouvez votre prochain grand livre, construisez votre bibliothèque personnelle et poursuivez votre lecture où que vous soyez.',
    uploadAdmin: "Téléversez un livre depuis la page admin pour l'ajouter à la bibliothèque Readify.",
    loadingBook: 'Chargement du livre...',
    unableOpenBook: "Impossible d'ouvrir ce livre",
    backBooks: '← Retour aux livres',
    noOriginalFile: 'Aucun fichier original',
    backBook: '← Retour au livre',
    back: '← Retour',
    page: 'Page',
    previous: '← Précédent',
    go: 'Aller',
    next: 'Suivant →',
    loadingPdf: 'Chargement du PDF...',
    unablePdf: "Impossible d'afficher ce PDF.",
    previousPage: '← Page précédente',
    nextPage: 'Page suivante →',
    catFiction: 'Fiction',
    catBusiness: 'Affaires',
    catSelfDevelopment: 'Développement personnel',
    catLiterature: 'Littérature',
    catBiography: 'Biographie',
    catHistory: 'Histoire',
    catEducation: 'Éducation',
    catTechnology: 'Technologie',
    catReligion: 'Religion',
    catRomance: 'Romance',
    catChildren: 'Livres pour enfants',
    catScience: 'Sciences',
    catPhilosophy: 'Philosophie',
    catEconomics: 'Économie',
    catChristianBible: 'Bible chrétienne',
    creatingAccount: 'Création du compte...',
    validEmailHint: 'Gmail, Yahoo, Hotmail, Outlook ou un autre e-mail valide.',
    categoryHint: 'Sélectionnez la catégorie qui décrit le mieux ce livre.',
  },
  es: {
    home: 'Inicio',
    search: 'Buscar',
    signIn: 'Iniciar sesión',
    register: 'Registrarse',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
    language: 'Idioma',
    categories: 'Categorías',
    library: 'Biblioteca',
    account: 'Cuenta',
    discover: 'Descubrir',
    read: 'Leer',
    learn: 'Aprender',
    yourDigitalBookshelf: 'Tu biblioteca digital',
    discoverBooks: 'Descubre libros que te encantarán.',
    browseBooks: 'Explorar libros',
    findNextBook: 'Encuentra tu próximo libro',
    searchLibrary: 'Buscar en la biblioteca',
    searchBy: 'Busca por título, autor, ISBN, categoría o palabra clave.',
    searchPlaceholder: 'Buscar título, autor, ISBN...',
    searching: 'Buscando...',
    searchingLibrary: 'Buscando en la biblioteca de Readify...',
    noBooks: 'No se encontraron libros',
    tryAnother: 'Prueba otro título, autor, ISBN o palabra clave.',
    welcomeBack: 'Bienvenido de nuevo',
    signInContinue: 'Inicia sesión para seguir leyendo tus libros.',
    email: 'Correo electrónico',
    password: 'Contraseña',
    createAccount: 'Crear cuenta',
    name: 'Nombre',
    confirmPassword: 'Confirmar contraseña',
    cancel: 'Cancelar',
    save: 'Guardar',
    saving: 'Guardando...',
    editProfile: 'Editar perfil',
    readifyMember: 'Miembro de Readify',
    about: 'Acerca de',
    books: 'Libros',
    bookmarks: 'Marcadores',
    progress: 'Progreso',
    myLibrary: 'Mi biblioteca',
    savedBooks: 'Tus libros guardados',
    readingProgress: 'Progreso de lectura',
    continueReading: 'Continúa leyendo',
    signOut: 'Cerrar sesión',
    signOutReadify: 'Cerrar sesión de Readify',
    yourReadingSpace: 'Tu espacio de lectura',
    loadingLibrary: 'Cargando tu biblioteca...',
    libraryEmpty: 'Tu biblioteca está vacía',
    exploreBooks: 'Explorar libros →',
    savedBooksTitle: 'Libros guardados',
    removeLibrary: 'Eliminar de la biblioteca',
    keepGoing: 'Sigue así',
    loadingProgress: 'Cargando tu progreso...',
    continueWhereLeft: 'Continúa leyendo donde lo dejaste.',
    readNow: 'Leer ahora →',
    listen: 'Escuchar',
    bookNotFound: 'Libro no encontrado',
    backToSearch: 'Volver a buscar',
    backDiscover: '← Volver a descubrir',
    aboutBook: 'Acerca de este libro',
    featured: 'Libros destacados',
    popular: 'Populares ahora',
    explore: 'Explorar →',
    viewAll: 'Ver todo →',
    allBooks: 'Todos los libros',
    readifyLibrary: 'Biblioteca Readify',
    noBooksYet: 'Aún no hay libros disponibles',
    uploadBookAdmin: 'Sube un libro desde la página de administración para añadirlo a la biblioteca Readify.',
    curated: 'Seleccionados para ti',
    readersChoosing: 'Los lectores eligen',
    browseInterest: 'Explorar por interés',
    exploreCategories: 'Explorar categorías',
    keepJourney: 'Continúa tu camino',
    nextChapter: 'Tu próximo capítulo comienza aquí.',
    openLibrary: 'Abrir mi biblioteca',
    fullName: 'Nombre completo',
    bio: 'Biografía',
    emailCannot: 'El correo no se puede cambiar aquí.',
    tellReaders: 'Cuéntales algo sobre ti a los lectores...',
    uploadBook: 'Subir libro',
    readifyAdmin: 'Administración de Readify',
    bookTitle: 'Título del libro',
    description: 'Descripción',
    authorName: 'Nombre del autor',
    publishedYear: 'Año de publicación',
    languageCode: 'Código de idioma',
    languageName: 'Nombre del idioma',
    rightsStatus: 'Estado de derechos',
    publicDomain: 'Dominio público',
    openLicense: 'Licencia abierta',
    authorized: 'Autorizado',
    unknown: 'Desconocido',
    coverUrl: 'URL de portada',
    sourceUrl: 'URL de origen',
    selectCategory: 'Selecciona una categoría',
    selectedFile: 'Archivo seleccionado',
    bookFile: 'Archivo del libro',
    settings: 'Configuración',
    forgotPassword: '¿Olvidaste tu contraseña?',
    joinReadify: 'Únete a Readify y empieza a construir tu biblioteca.',
    addToLibrary: 'Añadir a la biblioteca',
    addToLibraryQuestion: '¿Añadir a la biblioteca?',
    addToLibraryDescription: '¿Quieres añadir este libro a tu biblioteca personal?',
    no: 'No',
    yes: 'Sí',
    loadingCategories: 'Cargando categorías...',
    loadingBooks: 'Cargando libros...',
    viewAllBooks: 'Ver todos los libros',
    heroDescription: 'Encuentra tu próximo gran libro, crea tu biblioteca personal y mantén tu lectura en marcha dondequiera que estés.',
    uploadAdmin: 'Sube un libro desde la página de administración para añadirlo a la biblioteca Readify.',
    loadingBook: 'Cargando libro...',
    unableOpenBook: 'No se puede abrir este libro',
    backBooks: '← Volver a los libros',
    noOriginalFile: 'No hay archivo original',
    backBook: '← Volver al libro',
    back: '← Volver',
    page: 'Página',
    previous: '← Anterior',
    go: 'Ir',
    next: 'Siguiente →',
    loadingPdf: 'Cargando PDF...',
    unablePdf: 'No se puede mostrar este PDF.',
    previousPage: '← Página anterior',
    nextPage: 'Página siguiente →',
    catFiction: 'Ficción',
    catBusiness: 'Negocios',
    catSelfDevelopment: 'Desarrollo personal',
    catLiterature: 'Literatura',
    catBiography: 'Biografía',
    catHistory: 'Historia',
    catEducation: 'Educación',
    catTechnology: 'Tecnología',
    catReligion: 'Religión',
    catRomance: 'Romance',
    catChildren: 'Libros infantiles',
    catScience: 'Ciencia',
    catPhilosophy: 'Filosofía',
    catEconomics: 'Economía',
    catChristianBible: 'Biblia cristiana',
    creatingAccount: 'Creando cuenta...',
    validEmailHint: 'Gmail, Yahoo, Hotmail, Outlook u otro correo válido.',
    categoryHint: 'Selecciona la categoría que mejor describa este libro.',
  },
  de: {
    home: 'Startseite',
    search: 'Suchen',
    signIn: 'Anmelden',
    register: 'Registrieren',
    profile: 'Profil',
    logout: 'Abmelden',
    language: 'Sprache',
    categories: 'Kategorien',
    library: 'Bibliothek',
    account: 'Konto',
    discover: 'Entdecken',
    read: 'Lesen',
    learn: 'Lernen',
    yourDigitalBookshelf: 'Dein digitales Bücherregal',
    discoverBooks: 'Entdecke Bücher, die dir gefallen werden.',
    browseBooks: 'Bücher durchsuchen',
    findNextBook: 'Finde dein nächstes Buch',
    searchLibrary: 'Bibliothek durchsuchen',
    searchBy: 'Suche nach Titel, Autor, ISBN, Kategorie oder Stichwort.',
    searchPlaceholder: 'Titel, Autor, ISBN suchen...',
    searching: 'Suche...',
    searchingLibrary: 'Durchsuche die Readify-Bibliothek...',
    noBooks: 'Keine Bücher gefunden',
    tryAnother: 'Versuche einen anderen Titel, Autor, ISBN oder Suchbegriff.',
    welcomeBack: 'Willkommen zurück',
    signInContinue: 'Melde dich an, um weiterzulesen.',
    email: 'E-Mail',
    password: 'Passwort',
    createAccount: 'Konto erstellen',
    name: 'Name',
    confirmPassword: 'Passwort bestätigen',
    cancel: 'Abbrechen',
    save: 'Speichern',
    saving: 'Speichern...',
    editProfile: 'Profil bearbeiten',
    readifyMember: 'Readify-Mitglied',
    about: 'Über uns',
    books: 'Bücher',
    bookmarks: 'Lesezeichen',
    progress: 'Fortschritt',
    myLibrary: 'Meine Bibliothek',
    savedBooks: 'Deine gespeicherten Bücher',
    readingProgress: 'Lesefortschritt',
    continueReading: 'Lies weiter',
    signOut: 'Abmelden',
    signOutReadify: 'Von Readify abmelden',
    yourReadingSpace: 'Dein Lesebereich',
    loadingLibrary: 'Deine Bibliothek wird geladen...',
    libraryEmpty: 'Deine Bibliothek ist leer',
    exploreBooks: 'Bücher entdecken →',
    savedBooksTitle: 'Gespeicherte Bücher',
    removeLibrary: 'Aus Bibliothek entfernen',
    keepGoing: 'Weiter so',
    loadingProgress: 'Dein Fortschritt wird geladen...',
    continueWhereLeft: 'Lies dort weiter, wo du aufgehört hast.',
    readNow: 'Jetzt lesen →',
    listen: 'Anhören',
    bookNotFound: 'Buch nicht gefunden',
    backToSearch: 'Zurück zur Suche',
    backDiscover: '← Zurück zu Entdecken',
    aboutBook: 'Über dieses Buch',
    featured: 'Empfohlene Bücher',
    popular: 'Jetzt beliebt',
    explore: 'Entdecken →',
    viewAll: 'Alle ansehen →',
    allBooks: 'Alle Bücher',
    readifyLibrary: 'Readify-Bibliothek',
    noBooksYet: 'Noch keine Bücher verfügbar',
    uploadBookAdmin: 'Lade ein Buch über die Admin-Seite hoch, um es zur Readify-Bibliothek hinzuzufügen.',
    curated: 'Für dich ausgewählt',
    readersChoosing: 'Leser wählen',
    browseInterest: 'Nach Interesse durchsuchen',
    exploreCategories: 'Kategorien entdecken',
    keepJourney: 'Setze deine Reise fort',
    nextChapter: 'Dein nächstes Kapitel beginnt hier.',
    openLibrary: 'Meine Bibliothek öffnen',
    fullName: 'Vollständiger Name',
    bio: 'Biografie',
    emailCannot: 'Die E-Mail kann hier nicht geändert werden.',
    tellReaders: 'Erzähle den Lesern etwas über dich...',
    uploadBook: 'Buch hochladen',
    readifyAdmin: 'Readify-Administration',
    bookTitle: 'Buchtitel',
    description: 'Beschreibung',
    authorName: 'Autorenname',
    publishedYear: 'Veröffentlichungsjahr',
    languageCode: 'Sprachcode',
    languageName: 'Sprachname',
    rightsStatus: 'Rechtsstatus',
    publicDomain: 'Gemeinfrei',
    openLicense: 'Offene Lizenz',
    authorized: 'Autorisiert',
    unknown: 'Unbekannt',
    coverUrl: 'Cover-URL',
    sourceUrl: 'Quell-URL',
    selectCategory: 'Kategorie auswählen',
    selectedFile: 'Ausgewählte Datei',
    bookFile: 'Buchdatei',
    settings: 'Einstellungen',
    forgotPassword: 'Passwort vergessen?',
    joinReadify: 'Tritt Readify bei und baue deine Bibliothek auf.',
    addToLibrary: 'Zur Bibliothek hinzufügen',
    addToLibraryQuestion: 'Zur Bibliothek hinzufügen?',
    addToLibraryDescription: 'Möchtest du dieses Buch zu deiner persönlichen Bibliothek hinzufügen?',
    no: 'Nein',
    yes: 'Ja',
    loadingCategories: 'Kategorien werden geladen...',
    loadingBooks: 'Bücher werden geladen...',
    viewAllBooks: 'Alle Bücher ansehen',
    heroDescription: 'Finde dein nächstes großartiges Buch, baue deine persönliche Bibliothek auf und setze deine Lesereise überall fort.',
    uploadAdmin: 'Lade ein Buch über die Admin-Seite hoch, um es zur Readify-Bibliothek hinzuzufügen.',
    loadingBook: 'Buch wird geladen...',
    unableOpenBook: 'Dieses Buch kann nicht geöffnet werden',
    backBooks: '← Zurück zu den Büchern',
    noOriginalFile: 'Keine Originaldatei',
    backBook: '← Zurück zum Buch',
    back: '← Zurück',
    page: 'Seite',
    previous: '← Zurück',
    go: 'Los',
    next: 'Weiter →',
    loadingPdf: 'PDF wird geladen...',
    unablePdf: 'Diese PDF kann nicht angezeigt werden.',
    previousPage: '← Vorherige Seite',
    nextPage: 'Nächste Seite →',
    catFiction: 'Fiktion',
    catBusiness: 'Geschäft',
    catSelfDevelopment: 'Persönliche Entwicklung',
    catLiterature: 'Literatur',
    catBiography: 'Biografie',
    catHistory: 'Geschichte',
    catEducation: 'Bildung',
    catTechnology: 'Technologie',
    catReligion: 'Religion',
    catRomance: 'Romantik',
    catChildren: 'Kinderbücher',
    catScience: 'Wissenschaft',
    catPhilosophy: 'Philosophie',
    catEconomics: 'Wirtschaft',
    catChristianBible: 'Christliche Bibel',
    creatingAccount: 'Konto wird erstellt...',
    validEmailHint: 'Gmail, Yahoo, Hotmail, Outlook oder eine andere gültige E-Mail.',
    categoryHint: 'Wähle die Kategorie, die dieses Buch am besten beschreibt.',
  },
  zh: {
    home: '首页',
    search: '搜索',
    signIn: '登录',
    register: '注册',
    profile: '个人资料',
    logout: '退出',
    language: '语言',
    categories: '分类',
    library: '图书馆',
    account: '账户',
    discover: '发现',
    read: '阅读',
    learn: '学习',
    yourDigitalBookshelf: '你的数字书架',
    discoverBooks: '发现你喜欢的书籍。',
    browseBooks: '浏览书籍',
    findNextBook: '寻找你的下一本书',
    searchLibrary: '搜索图书馆',
    searchBy: '按书名、作者、ISBN、类别或关键词搜索。',
    searchPlaceholder: '搜索书名、作者、ISBN...',
    searching: '搜索中...',
    searchingLibrary: '正在搜索 Readify 图书馆...',
    noBooks: '未找到书籍',
    tryAnother: '请尝试其他书名、作者、ISBN或关键词。',
    welcomeBack: '欢迎回来',
    signInContinue: '登录以继续阅读你的书籍。',
    email: '电子邮件',
    password: '密码',
    createAccount: '创建账户',
    name: '姓名',
    confirmPassword: '确认密码',
    cancel: '取消',
    save: '保存',
    saving: '保存中...',
    editProfile: '编辑个人资料',
    readifyMember: 'Readify会员',
    about: '关于',
    books: '书籍',
    bookmarks: '书签',
    progress: '进度',
    myLibrary: '我的图书馆',
    savedBooks: '你保存的书籍',
    readingProgress: '阅读进度',
    continueReading: '继续阅读',
    signOut: 'ログアウト',
    signOutReadify: '退出 Readify',
    yourReadingSpace: '你的阅读空间',
    loadingLibrary: '正在加载你的图书馆...',
    libraryEmpty: '你的图书馆为空',
    exploreBooks: '探索书籍 →',
    savedBooksTitle: '已保存的书籍',
    removeLibrary: '从图书馆移除',
    keepGoing: '继续阅读',
    loadingProgress: '正在加载你的进度...',
    continueWhereLeft: '从上次停下的地方继续阅读。',
    readNow: '立即阅读 →',
    listen: '收听',
    bookNotFound: '未找到书籍',
    backToSearch: '返回搜索',
    backDiscover: '← 返回发现',
    aboutBook: '关于本书',
    featured: '精选书籍',
    popular: '当前热门',
    explore: '探索 →',
    viewAll: '查看全部 →',
    allBooks: '所有书籍',
    readifyLibrary: 'Readify图书馆',
    noBooksYet: '暂无书籍',
    uploadBookAdmin: '从管理员页面上传书籍，将其添加到 Readify 图书馆。',
    curated: '为你精选',
    readersChoosing: '读者正在选择',
    browseInterest: '按兴趣浏览',
    exploreCategories: '探索分类',
    keepJourney: '继续你的旅程',
    nextChapter: '你的下一章从这里开始。',
    openLibrary: '打开我的图书馆',
    fullName: '姓名',
    bio: '简介',
    emailCannot: '此处无法更改电子邮件。',
    tellReaders: '告诉读者一些关于你的事情...',
    uploadBook: '上传书籍',
    readifyAdmin: 'Readify 管理',
    bookTitle: '书名',
    description: '描述',
    authorName: '作者姓名',
    publishedYear: '出版年份',
    languageCode: '语言代码',
    languageName: '语言名称',
    rightsStatus: '版权状态',
    publicDomain: '公版',
    openLicense: '开放许可',
    authorized: '已授权',
    unknown: '未知',
    coverUrl: '封面URL',
    sourceUrl: '来源URL',
    selectCategory: '选择类别',
    selectedFile: '已选文件',
    bookFile: '书籍文件',
    settings: '设置',
    forgotPassword: '忘记密码？',
    joinReadify: '加入 Readify，开始建立你的图书馆。',
    addToLibrary: '添加到图书馆',
    addToLibraryQuestion: '添加到图书馆？',
    addToLibraryDescription: '要将这本书添加到你的个人图书馆吗？',
    no: '否',
    yes: '是',
    loadingCategories: '正在加载分类...',
    loadingBooks: '正在加载书籍...',
    viewAllBooks: '查看所有书籍',
    heroDescription: '找到下一本好书，建立个人图书馆，无论身在何处都能继续阅读。',
    uploadAdmin: '从管理员页面上传书籍，将其添加到 Readify 图书馆。',
    loadingBook: '正在加载书籍...',
    unableOpenBook: '无法打开此书',
    backBooks: '← 返回书籍',
    noOriginalFile: '没有原始文件',
    backBook: '← 返回本书',
    back: '← 返回',
    page: '页',
    previous: '← 上一页',
    go: '前往',
    next: '下一页 →',
    loadingPdf: '正在加载PDF...',
    unablePdf: '无法显示此PDF。',
    previousPage: '← 上一页',
    nextPage: '下一页 →',
    catFiction: '小说',
    catBusiness: '商业',
    catSelfDevelopment: '自我发展',
    catLiterature: '文学',
    catBiography: '传记',
    catHistory: '历史',
    catEducation: '教育',
    catTechnology: '技术',
    catReligion: '宗教',
    catRomance: '爱情',
    catChildren: '儿童读物',
    catScience: '科学',
    catPhilosophy: '哲学',
    catEconomics: '经济学',
    catChristianBible: '基督教圣经',
    creatingAccount: '正在创建账户...',
    validEmailHint: 'Gmail、Yahoo、Hotmail、Outlook或其他有效邮箱。',
    categoryHint: '选择最能描述本书的类别。',
  },
  ja: {
    home: 'ホーム',
    search: '検索',
    signIn: 'ログイン',
    register: '登録',
    profile: 'プロフィール',
    logout: 'ログアウト',
    language: '言語',
    categories: 'カテゴリー',
    library: 'ライブラリ',
    account: 'アカウント',
    discover: '発見',
    read: '読む',
    learn: '学ぶ',
    yourDigitalBookshelf: 'あなたのデジタル本棚',
    discoverBooks: 'お気に入りの本を見つけよう。',
    browseBooks: '本を探す',
    findNextBook: '次の本を見つけよう',
    searchLibrary: 'ライブラリを検索',
    searchBy: 'タイトル、著者、ISBN、カテゴリー、キーワードで検索。',
    searchPlaceholder: 'タイトル、著者、ISBNを検索...',
    searching: '検索中...',
    searchingLibrary: 'Readifyライブラリを検索中...',
    noBooks: '本が見つかりません',
    tryAnother: '別のタイトル、著者、ISBN、キーワードを試してください。',
    welcomeBack: 'おかえりなさい',
    signInContinue: 'ログインして読書を続けましょう。',
    email: 'メール',
    password: 'パスワード',
    createAccount: 'アカウントを作成',
    name: '名前',
    confirmPassword: 'パスワードを確認',
    cancel: 'キャンセル',
    save: '保存',
    saving: '保存中...',
    editProfile: 'プロフィールを編集',
    readifyMember: 'Readifyメンバー',
    about: '概要',
    books: '本',
    bookmarks: 'ブックマーク',
    progress: '進捗',
    myLibrary: 'マイライブラリ',
    savedBooks: '保存した本',
    readingProgress: '読書の進捗',
    continueReading: '読書を続ける',
    signOut: '退出登录',
    signOutReadify: 'Readifyからログアウト',
    yourReadingSpace: 'あなたの読書スペース',
    loadingLibrary: 'ライブラリを読み込んでいます...',
    libraryEmpty: 'ライブラリは空です',
    exploreBooks: '本を探す →',
    savedBooksTitle: '保存した本',
    removeLibrary: 'ライブラリから削除',
    keepGoing: '続けましょう',
    loadingProgress: '進捗を読み込んでいます...',
    continueWhereLeft: '前回の続きから読みましょう。',
    readNow: '今すぐ読む →',
    listen: '聴く',
    bookNotFound: '本が見つかりません',
    backToSearch: '検索に戻る',
    backDiscover: '← 発見に戻る',
    aboutBook: 'この本について',
    featured: 'おすすめの本',
    popular: '現在人気',
    explore: '探索 →',
    viewAll: 'すべて見る →',
    allBooks: 'すべての本',
    readifyLibrary: 'Readifyライブラリ',
    noBooksYet: 'まだ本がありません',
    uploadBookAdmin: '管理ページから本をアップロードしてReadifyライブラリに追加します。',
    curated: 'あなた向けに厳選',
    readersChoosing: '読者が選んでいます',
    browseInterest: '興味から探す',
    exploreCategories: 'カテゴリーを探索',
    keepJourney: '読書の旅を続ける',
    nextChapter: '次の章はここから始まります。',
    openLibrary: 'マイライブラリを開く',
    fullName: '氏名',
    bio: '自己紹介',
    emailCannot: 'ここではメールを変更できません。',
    tellReaders: '読者にあなたのことを伝えましょう...',
    uploadBook: '本をアップロード',
    readifyAdmin: 'Readify管理',
    bookTitle: '本のタイトル',
    description: '説明',
    authorName: '著者名',
    publishedYear: '出版年',
    languageCode: '言語コード',
    languageName: '言語名',
    rightsStatus: '権利ステータス',
    publicDomain: 'パブリックドメイン',
    openLicense: 'オープンライセンス',
    authorized: '承認済み',
    unknown: '不明',
    coverUrl: '表紙URL',
    sourceUrl: 'ソースURL',
    selectCategory: 'カテゴリーを選択',
    selectedFile: '選択したファイル',
    bookFile: '本のファイル',
    settings: '設定',
    forgotPassword: 'パスワードを忘れましたか？',
    joinReadify: 'Readifyに参加してライブラリを作りましょう。',
    addToLibrary: 'ライブラリに追加',
    addToLibraryQuestion: 'ライブラリに追加しますか？',
    addToLibraryDescription: 'この本を個人ライブラリに追加しますか？',
    no: 'いいえ',
    yes: 'はい',
    loadingCategories: 'カテゴリーを読み込んでいます...',
    loadingBooks: '本を読み込んでいます...',
    viewAllBooks: 'すべての本を見る',
    heroDescription: '次の素晴らしい本を見つけ、個人ライブラリを作り、どこにいても読書を続けましょう。',
    uploadAdmin: '管理ページから本をアップロードしてReadifyライブラリに追加します。',
    loadingBook: '本を読み込んでいます...',
    unableOpenBook: 'この本を開けません',
    backBooks: '← 本に戻る',
    noOriginalFile: '元ファイルなし',
    backBook: '← 本に戻る',
    back: '← 戻る',
    page: 'ページ',
    previous: '← 前へ',
    go: '移動',
    next: '次へ →',
    loadingPdf: 'PDFを読み込んでいます...',
    unablePdf: 'このPDFを表示できません。',
    previousPage: '← 前のページ',
    nextPage: '次のページ →',
    catFiction: 'フィクション',
    catBusiness: 'ビジネス',
    catSelfDevelopment: '自己啓発',
    catLiterature: '文学',
    catBiography: '伝記',
    catHistory: '歴史',
    catEducation: '教育',
    catTechnology: 'テクノロジー',
    catReligion: '宗教',
    catRomance: 'ロマンス',
    catChildren: '児童書',
    catScience: '科学',
    catPhilosophy: '哲学',
    catEconomics: '経済学',
    catChristianBible: 'キリスト教聖書',
    creatingAccount: 'アカウントを作成中...',
    validEmailHint: 'Gmail、Yahoo、Hotmail、Outlookなどの有効なメールアドレス。',
    categoryHint: 'この本を最もよく表すカテゴリーを選択してください。',
  },
  ar: {
    home: 'الرئيسية',
    search: 'بحث',
    signIn: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    profile: 'الملف الشخصي',
    logout: 'تسجيل الخروج',
    language: 'اللغة',
    categories: 'الفئات',
    library: 'المكتبة',
    account: 'الحساب',
    discover: 'اكتشف',
    read: 'اقرأ',
    learn: 'تعلم',
    yourDigitalBookshelf: 'مكتبتك الرقمية',
    discoverBooks: 'اكتشف الكتب التي ستحبها.',
    browseBooks: 'تصفح الكتب',
    findNextBook: 'اعثر على كتابك التالي',
    searchLibrary: 'البحث في المكتبة',
    searchBy: 'ابحث بالعنوان أو المؤلف أو ISBN أو الفئة أو الكلمة المفتاحية.',
    searchPlaceholder: 'ابحث عن العنوان أو المؤلف أو ISBN...',
    searching: 'جارٍ البحث...',
    searchingLibrary: 'جارٍ البحث في مكتبة Readify...',
    noBooks: 'لم يتم العثور على كتب',
    tryAnother: 'جرّب عنوانًا أو مؤلفًا أو ISBN أو كلمة مفتاحية أخرى.',
    welcomeBack: 'مرحبًا بعودتك',
    signInContinue: 'سجّل الدخول لمتابعة قراءة كتبك.',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    createAccount: 'إنشاء حساب',
    name: 'الاسم',
    confirmPassword: 'تأكيد كلمة المرور',
    cancel: 'إلغاء',
    save: 'حفظ',
    saving: 'جارٍ الحفظ...',
    editProfile: 'تعديل الملف الشخصي',
    readifyMember: 'عضو Readify',
    about: 'حول',
    books: 'الكتب',
    bookmarks: 'الإشارات المرجعية',
    progress: 'التقدم',
    myLibrary: 'مكتبتي',
    savedBooks: 'كتبك المحفوظة',
    readingProgress: 'تقدم القراءة',
    continueReading: 'تابع القراءة',
    signOut: 'تسجيل الخروج',
    signOutReadify: 'تسجيل الخروج من Readify',
    yourReadingSpace: 'مساحة القراءة الخاصة بك',
    loadingLibrary: 'جارٍ تحميل مكتبتك...',
    libraryEmpty: 'مكتبتك فارغة',
    exploreBooks: 'استكشف الكتب ←',
    savedBooksTitle: 'الكتب المحفوظة',
    removeLibrary: 'إزالة من المكتبة',
    keepGoing: 'واصل',
    loadingProgress: 'جارٍ تحميل تقدمك...',
    continueWhereLeft: 'تابع القراءة من حيث توقفت.',
    readNow: 'اقرأ الآن ←',
    listen: 'استمع',
    bookNotFound: 'الكتاب غير موجود',
    backToSearch: 'العودة إلى البحث',
    backDiscover: '← العودة إلى الاكتشاف',
    aboutBook: 'حول هذا الكتاب',
    featured: 'الكتب المميزة',
    popular: 'الشائعة الآن',
    explore: 'استكشف ←',
    viewAll: 'عرض الكل ←',
    allBooks: 'جميع الكتب',
    readifyLibrary: 'مكتبة Readify',
    noBooksYet: 'لا توجد كتب متاحة بعد',
    uploadBookAdmin: 'حمّل كتابًا من صفحة الإدارة لإضافته إلى مكتبة Readify.',
    curated: 'مختارة لك',
    readersChoosing: 'اختيارات القراء',
    browseInterest: 'تصفح حسب الاهتمام',
    exploreCategories: 'استكشف الفئات',
    keepJourney: 'واصل رحلتك',
    nextChapter: 'فصلك التالي يبدأ هنا.',
    openLibrary: 'افتح مكتبتي',
    fullName: 'الاسم الكامل',
    bio: 'نبذة',
    emailCannot: 'لا يمكن تغيير البريد الإلكتروني هنا.',
    tellReaders: 'أخبر القراء شيئًا عن نفسك...',
    uploadBook: 'تحميل كتاب',
    readifyAdmin: 'إدارة Readify',
    bookTitle: 'عنوان الكتاب',
    description: 'الوصف',
    authorName: 'اسم المؤلف',
    publishedYear: 'سنة النشر',
    languageCode: 'رمز اللغة',
    languageName: 'اسم اللغة',
    rightsStatus: 'حالة الحقوق',
    publicDomain: 'الملك العام',
    openLicense: 'ترخيص مفتوح',
    authorized: 'مصرح به',
    unknown: 'غير معروف',
    coverUrl: 'رابط الغلاف',
    sourceUrl: 'رابط المصدر',
    selectCategory: 'اختر فئة',
    selectedFile: 'الملف المحدد',
    bookFile: 'ملف الكتاب',
    settings: 'الإعدادات',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    joinReadify: 'انضم إلى Readify وابدأ ببناء مكتبتك.',
    addToLibrary: 'إضافة إلى المكتبة',
    addToLibraryQuestion: 'إضافة إلى المكتبة؟',
    addToLibraryDescription: 'هل تريد إضافة هذا الكتاب إلى مكتبتك الشخصية؟',
    no: 'لا',
    yes: 'نعم',
    loadingCategories: 'جارٍ تحميل الفئات...',
    loadingBooks: 'جارٍ تحميل الكتب...',
    viewAllBooks: 'عرض جميع الكتب',
    heroDescription: 'اعثر على كتابك الرائع التالي، وابنِ مكتبتك الشخصية، وواصل رحلة القراءة أينما كنت.',
    uploadAdmin: 'حمّل كتابًا من صفحة الإدارة لإضافته إلى مكتبة Readify.',
    loadingBook: 'جارٍ تحميل الكتاب...',
    unableOpenBook: 'تعذر فتح هذا الكتاب',
    backBooks: '← العودة إلى الكتب',
    noOriginalFile: 'لا يوجد ملف أصلي',
    backBook: '← العودة إلى الكتاب',
    back: '← رجوع',
    page: 'صفحة',
    previous: '← السابق',
    go: 'اذهب',
    next: 'التالي →',
    loadingPdf: 'جارٍ تحميل PDF...',
    unablePdf: 'تعذر عرض ملف PDF هذا.',
    previousPage: '← الصفحة السابقة',
    nextPage: 'الصفحة التالية ←',
    catFiction: 'خيال',
    catBusiness: 'الأعمال',
    catSelfDevelopment: 'التنمية الذاتية',
    catLiterature: 'الأدب',
    catBiography: 'السيرة الذاتية',
    catHistory: 'التاريخ',
    catEducation: 'التعليم',
    catTechnology: 'التكنولوجيا',
    catReligion: 'الدين',
    catRomance: 'الرومانسية',
    catChildren: 'كتب الأطفال',
    catScience: 'العلوم',
    catPhilosophy: 'الفلسفة',
    catEconomics: 'الاقتصاد',
    catChristianBible: 'الكتاب المقدس المسيحي',
    creatingAccount: 'جارٍ إنشاء الحساب...',
    validEmailHint: 'Gmail أو Yahoo أو Hotmail أو Outlook أو بريد إلكتروني صالح آخر.',
    categoryHint: 'اختر الفئة التي تصف هذا الكتاب بشكل أفضل.',
  },
};

export function getTranslation(language, key) {
  return translations[language]?.[key] ?? translations.en[key] ?? key;
};